// Code generated by protoc-gen-go.
// source: beans.horse.proto
// DO NOT EDIT!

/*
Package beans is a generated protocol buffer package.

It is generated from these files:
	beans.horse.proto

It has these top-level messages:
	CreateRoomBean
	JoinRoomBean
	PlayerDeviceBean
	PlagerJoinGameBean
	PlayerLeaveGameBean
	HorseSpeedBean
	ServerResponseCreateRoomBean
	ServerResponseJoinRoomBean
	ServerSendBean
	ClientRequestBean
*/
package beans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// *
// client -> server
type RequestOperationCode int32

const (
	RequestOperationCode_REQUEST_OPERATIONCODE_PLAYERDEVICCEBEAN RequestOperationCode = 1
	RequestOperationCode_REQUEST_OPERATIONCODE_CREATEROOM        RequestOperationCode = 2
	RequestOperationCode_REQUEST_OPERATIONCODE_JOINROOM          RequestOperationCode = 3
)

var RequestOperationCode_name = map[int32]string{
	1: "REQUEST_OPERATIONCODE_PLAYERDEVICCEBEAN",
	2: "REQUEST_OPERATIONCODE_CREATEROOM",
	3: "REQUEST_OPERATIONCODE_JOINROOM",
}
var RequestOperationCode_value = map[string]int32{
	"REQUEST_OPERATIONCODE_PLAYERDEVICCEBEAN": 1,
	"REQUEST_OPERATIONCODE_CREATEROOM":        2,
	"REQUEST_OPERATIONCODE_JOINROOM":          3,
}

func (x RequestOperationCode) Enum() *RequestOperationCode {
	p := new(RequestOperationCode)
	*p = x
	return p
}
func (x RequestOperationCode) String() string {
	return proto.EnumName(RequestOperationCode_name, int32(x))
}
func (x *RequestOperationCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestOperationCode_value, data, "RequestOperationCode")
	if err != nil {
		return err
	}
	*x = RequestOperationCode(value)
	return nil
}
func (RequestOperationCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// *
// server -> client
type SendMessageOperationCode int32

const (
	SendMessageOperationCode_SENDMESSAGE_OPERATIONCODE_RESPONSE        SendMessageOperationCode = 1
	SendMessageOperationCode_SENDMESSAGE_OPERATIONCODE_PLAYERJOINGAME  SendMessageOperationCode = 2
	SendMessageOperationCode_SENDMESSAGE_OPERATIONCODE_PLAYERDEVICE    SendMessageOperationCode = 3
	SendMessageOperationCode_SENDMESSAGE_OPERATIONCODE_HORSEGAME_SPEED SendMessageOperationCode = 4
)

var SendMessageOperationCode_name = map[int32]string{
	1: "SENDMESSAGE_OPERATIONCODE_RESPONSE",
	2: "SENDMESSAGE_OPERATIONCODE_PLAYERJOINGAME",
	3: "SENDMESSAGE_OPERATIONCODE_PLAYERDEVICE",
	4: "SENDMESSAGE_OPERATIONCODE_HORSEGAME_SPEED",
}
var SendMessageOperationCode_value = map[string]int32{
	"SENDMESSAGE_OPERATIONCODE_RESPONSE":        1,
	"SENDMESSAGE_OPERATIONCODE_PLAYERJOINGAME":  2,
	"SENDMESSAGE_OPERATIONCODE_PLAYERDEVICE":    3,
	"SENDMESSAGE_OPERATIONCODE_HORSEGAME_SPEED": 4,
}

func (x SendMessageOperationCode) Enum() *SendMessageOperationCode {
	p := new(SendMessageOperationCode)
	*p = x
	return p
}
func (x SendMessageOperationCode) String() string {
	return proto.EnumName(SendMessageOperationCode_name, int32(x))
}
func (x *SendMessageOperationCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SendMessageOperationCode_value, data, "SendMessageOperationCode")
	if err != nil {
		return err
	}
	*x = SendMessageOperationCode(value)
	return nil
}
func (SendMessageOperationCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// *
// client -> server
// 创建房间
type CreateRoomBean struct {
	GameId           *string  `protobuf:"bytes,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	Longitude        *float32 `protobuf:"fixed32,2,opt,name=longitude,def=0" json:"longitude,omitempty"`
	Latitude         *float32 `protobuf:"fixed32,3,opt,name=latitude,def=0" json:"latitude,omitempty"`
	Ip               *string  `protobuf:"bytes,4,opt,name=ip,def=0.0.0.0" json:"ip,omitempty"`
	DeviceInfo       *string  `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CreateRoomBean) Reset()                    { *m = CreateRoomBean{} }
func (m *CreateRoomBean) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomBean) ProtoMessage()               {}
func (*CreateRoomBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_CreateRoomBean_Longitude float32 = 0
const Default_CreateRoomBean_Latitude float32 = 0
const Default_CreateRoomBean_Ip string = "0.0.0.0"

func (m *CreateRoomBean) GetGameId() string {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return ""
}

func (m *CreateRoomBean) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return Default_CreateRoomBean_Longitude
}

func (m *CreateRoomBean) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return Default_CreateRoomBean_Latitude
}

func (m *CreateRoomBean) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return Default_CreateRoomBean_Ip
}

func (m *CreateRoomBean) GetDeviceInfo() string {
	if m != nil && m.DeviceInfo != nil {
		return *m.DeviceInfo
	}
	return ""
}

// *
// client -> server
// 申请加入房间
type JoinRoomBean struct {
	GameId           *string  `protobuf:"bytes,6,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	Tocken           *string  `protobuf:"bytes,1,opt,name=tocken" json:"tocken,omitempty"`
	Longitude        *float32 `protobuf:"fixed32,2,opt,name=longitude,def=0" json:"longitude,omitempty"`
	Latitude         *float32 `protobuf:"fixed32,3,opt,name=latitude,def=0" json:"latitude,omitempty"`
	Ip               *string  `protobuf:"bytes,4,opt,name=ip,def=0.0.0.0" json:"ip,omitempty"`
	DeviceInfo       *string  `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *JoinRoomBean) Reset()                    { *m = JoinRoomBean{} }
func (m *JoinRoomBean) String() string            { return proto.CompactTextString(m) }
func (*JoinRoomBean) ProtoMessage()               {}
func (*JoinRoomBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_JoinRoomBean_Longitude float32 = 0
const Default_JoinRoomBean_Latitude float32 = 0
const Default_JoinRoomBean_Ip string = "0.0.0.0"

func (m *JoinRoomBean) GetGameId() string {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return ""
}

func (m *JoinRoomBean) GetTocken() string {
	if m != nil && m.Tocken != nil {
		return *m.Tocken
	}
	return ""
}

func (m *JoinRoomBean) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return Default_JoinRoomBean_Longitude
}

func (m *JoinRoomBean) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return Default_JoinRoomBean_Latitude
}

func (m *JoinRoomBean) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return Default_JoinRoomBean_Ip
}

func (m *JoinRoomBean) GetDeviceInfo() string {
	if m != nil && m.DeviceInfo != nil {
		return *m.DeviceInfo
	}
	return ""
}

// *
// client -> server
// server -> client
// player_client端陀螺仪信息
type PlayerDeviceBean struct {
	Tocken           *string  `protobuf:"bytes,11,opt,name=tocken" json:"tocken,omitempty"`
	GameId           *string  `protobuf:"bytes,10,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	AngleAlpha       *float32 `protobuf:"fixed32,1,opt,name=angle_alpha,json=angleAlpha,def=0" json:"angle_alpha,omitempty"`
	AngleBeta        *float32 `protobuf:"fixed32,2,opt,name=angle_beta,json=angleBeta,def=0" json:"angle_beta,omitempty"`
	AngleGamma       *float32 `protobuf:"fixed32,3,opt,name=angle_gamma,json=angleGamma,def=0" json:"angle_gamma,omitempty"`
	AcceX            *float32 `protobuf:"fixed32,4,opt,name=acce_x,json=acceX,def=0" json:"acce_x,omitempty"`
	AcceY            *float32 `protobuf:"fixed32,5,opt,name=acce_y,json=acceY,def=0" json:"acce_y,omitempty"`
	AcceZ            *float32 `protobuf:"fixed32,6,opt,name=acce_z,json=acceZ,def=0" json:"acce_z,omitempty"`
	AcceAlpha        *float32 `protobuf:"fixed32,7,opt,name=acce_alpha,json=acceAlpha,def=0" json:"acce_alpha,omitempty"`
	AcceBeta         *float32 `protobuf:"fixed32,8,opt,name=acce_beta,json=acceBeta,def=0" json:"acce_beta,omitempty"`
	AcceGamma        *float32 `protobuf:"fixed32,9,opt,name=acce_gamma,json=acceGamma,def=0" json:"acce_gamma,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PlayerDeviceBean) Reset()                    { *m = PlayerDeviceBean{} }
func (m *PlayerDeviceBean) String() string            { return proto.CompactTextString(m) }
func (*PlayerDeviceBean) ProtoMessage()               {}
func (*PlayerDeviceBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_PlayerDeviceBean_AngleAlpha float32 = 0
const Default_PlayerDeviceBean_AngleBeta float32 = 0
const Default_PlayerDeviceBean_AngleGamma float32 = 0
const Default_PlayerDeviceBean_AcceX float32 = 0
const Default_PlayerDeviceBean_AcceY float32 = 0
const Default_PlayerDeviceBean_AcceZ float32 = 0
const Default_PlayerDeviceBean_AcceAlpha float32 = 0
const Default_PlayerDeviceBean_AcceBeta float32 = 0
const Default_PlayerDeviceBean_AcceGamma float32 = 0

func (m *PlayerDeviceBean) GetTocken() string {
	if m != nil && m.Tocken != nil {
		return *m.Tocken
	}
	return ""
}

func (m *PlayerDeviceBean) GetGameId() string {
	if m != nil && m.GameId != nil {
		return *m.GameId
	}
	return ""
}

func (m *PlayerDeviceBean) GetAngleAlpha() float32 {
	if m != nil && m.AngleAlpha != nil {
		return *m.AngleAlpha
	}
	return Default_PlayerDeviceBean_AngleAlpha
}

func (m *PlayerDeviceBean) GetAngleBeta() float32 {
	if m != nil && m.AngleBeta != nil {
		return *m.AngleBeta
	}
	return Default_PlayerDeviceBean_AngleBeta
}

func (m *PlayerDeviceBean) GetAngleGamma() float32 {
	if m != nil && m.AngleGamma != nil {
		return *m.AngleGamma
	}
	return Default_PlayerDeviceBean_AngleGamma
}

func (m *PlayerDeviceBean) GetAcceX() float32 {
	if m != nil && m.AcceX != nil {
		return *m.AcceX
	}
	return Default_PlayerDeviceBean_AcceX
}

func (m *PlayerDeviceBean) GetAcceY() float32 {
	if m != nil && m.AcceY != nil {
		return *m.AcceY
	}
	return Default_PlayerDeviceBean_AcceY
}

func (m *PlayerDeviceBean) GetAcceZ() float32 {
	if m != nil && m.AcceZ != nil {
		return *m.AcceZ
	}
	return Default_PlayerDeviceBean_AcceZ
}

func (m *PlayerDeviceBean) GetAcceAlpha() float32 {
	if m != nil && m.AcceAlpha != nil {
		return *m.AcceAlpha
	}
	return Default_PlayerDeviceBean_AcceAlpha
}

func (m *PlayerDeviceBean) GetAcceBeta() float32 {
	if m != nil && m.AcceBeta != nil {
		return *m.AcceBeta
	}
	return Default_PlayerDeviceBean_AcceBeta
}

func (m *PlayerDeviceBean) GetAcceGamma() float32 {
	if m != nil && m.AcceGamma != nil {
		return *m.AcceGamma
	}
	return Default_PlayerDeviceBean_AcceGamma
}

// *
// server -> client
// player_client加入游戏后，server向game_client发送的新加入的player_client的信息
type PlagerJoinGameBean struct {
	PlayerTocken     *string `protobuf:"bytes,1,opt,name=player_tocken,json=playerTocken" json:"player_tocken,omitempty"`
	PlayerName       *string `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	PlayerLevel      *int32  `protobuf:"varint,3,opt,name=player_level,json=playerLevel" json:"player_level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlagerJoinGameBean) Reset()                    { *m = PlagerJoinGameBean{} }
func (m *PlagerJoinGameBean) String() string            { return proto.CompactTextString(m) }
func (*PlagerJoinGameBean) ProtoMessage()               {}
func (*PlagerJoinGameBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PlagerJoinGameBean) GetPlayerTocken() string {
	if m != nil && m.PlayerTocken != nil {
		return *m.PlayerTocken
	}
	return ""
}

func (m *PlagerJoinGameBean) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *PlagerJoinGameBean) GetPlayerLevel() int32 {
	if m != nil && m.PlayerLevel != nil {
		return *m.PlayerLevel
	}
	return 0
}

// *
// server -> client
// player_client离开游戏后server向game_client发送的离开房间的player_client的信息
type PlayerLeaveGameBean struct {
	PlayerTocken     *string `protobuf:"bytes,1,opt,name=player_tocken,json=playerTocken" json:"player_tocken,omitempty"`
	PlayerName       *string `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	PlayerLevel      *int32  `protobuf:"varint,3,opt,name=player_level,json=playerLevel" json:"player_level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerLeaveGameBean) Reset()                    { *m = PlayerLeaveGameBean{} }
func (m *PlayerLeaveGameBean) String() string            { return proto.CompactTextString(m) }
func (*PlayerLeaveGameBean) ProtoMessage()               {}
func (*PlayerLeaveGameBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PlayerLeaveGameBean) GetPlayerTocken() string {
	if m != nil && m.PlayerTocken != nil {
		return *m.PlayerTocken
	}
	return ""
}

func (m *PlayerLeaveGameBean) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *PlayerLeaveGameBean) GetPlayerLevel() int32 {
	if m != nil && m.PlayerLevel != nil {
		return *m.PlayerLevel
	}
	return 0
}

// *
// server -> client
// 赛马游戏中马的速度
type HorseSpeedBean struct {
	PlayerTocken     *string  `protobuf:"bytes,1,opt,name=player_tocken,json=playerTocken" json:"player_tocken,omitempty"`
	PlayerName       *string  `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	PlayerLevel      *int32   `protobuf:"varint,3,opt,name=player_level,json=playerLevel" json:"player_level,omitempty"`
	PlayerSpeed      *float32 `protobuf:"fixed32,4,opt,name=player_speed,json=playerSpeed" json:"player_speed,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HorseSpeedBean) Reset()                    { *m = HorseSpeedBean{} }
func (m *HorseSpeedBean) String() string            { return proto.CompactTextString(m) }
func (*HorseSpeedBean) ProtoMessage()               {}
func (*HorseSpeedBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HorseSpeedBean) GetPlayerTocken() string {
	if m != nil && m.PlayerTocken != nil {
		return *m.PlayerTocken
	}
	return ""
}

func (m *HorseSpeedBean) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *HorseSpeedBean) GetPlayerLevel() int32 {
	if m != nil && m.PlayerLevel != nil {
		return *m.PlayerLevel
	}
	return 0
}

func (m *HorseSpeedBean) GetPlayerSpeed() float32 {
	if m != nil && m.PlayerSpeed != nil {
		return *m.PlayerSpeed
	}
	return 0
}

// *
// 针对game_client创建房间请求的响应
type ServerResponseCreateRoomBean struct {
	MaxCount         *int32  `protobuf:"varint,1,opt,name=max_count,json=maxCount,def=0" json:"max_count,omitempty"`
	RoomId           *string `protobuf:"bytes,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerResponseCreateRoomBean) Reset()                    { *m = ServerResponseCreateRoomBean{} }
func (m *ServerResponseCreateRoomBean) String() string            { return proto.CompactTextString(m) }
func (*ServerResponseCreateRoomBean) ProtoMessage()               {}
func (*ServerResponseCreateRoomBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

const Default_ServerResponseCreateRoomBean_MaxCount int32 = 0

func (m *ServerResponseCreateRoomBean) GetMaxCount() int32 {
	if m != nil && m.MaxCount != nil {
		return *m.MaxCount
	}
	return Default_ServerResponseCreateRoomBean_MaxCount
}

func (m *ServerResponseCreateRoomBean) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

// *
// 针对player_client申请加入房间的响应
type ServerResponseJoinRoomBean struct {
	RoomId           *string `protobuf:"bytes,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerResponseJoinRoomBean) Reset()                    { *m = ServerResponseJoinRoomBean{} }
func (m *ServerResponseJoinRoomBean) String() string            { return proto.CompactTextString(m) }
func (*ServerResponseJoinRoomBean) ProtoMessage()               {}
func (*ServerResponseJoinRoomBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ServerResponseJoinRoomBean) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

// *
// server -> client
// server向client发送的数据(响应，玩家加入与离开，玩家陀螺仪数据等)
type ServerSendBean struct {
	ResultCode *int32                `protobuf:"varint,1,opt,name=result_code,json=resultCode,def=0" json:"result_code,omitempty"`
	RequestId  *string               `protobuf:"bytes,2,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	Desc       *string               `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	OptionCode *RequestOperationCode `protobuf:"varint,4,opt,name=option_code,json=optionCode,enum=beans.RequestOperationCode" json:"option_code,omitempty"`
	// Types that are valid to be assigned to Bean:
	//	*ServerSendBean_ResponseCreateroomBean
	//	*ServerSendBean_ResponseJoinroomBean
	//	*ServerSendBean_PlayerJoinBean
	//	*ServerSendBean_PlayerLevelBean
	//	*ServerSendBean_PlayerDeviceBean
	//	*ServerSendBean_PlayerHorsesgameSpeedBean
	Bean             isServerSendBean_Bean `protobuf_oneof:"Bean"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ServerSendBean) Reset()                    { *m = ServerSendBean{} }
func (m *ServerSendBean) String() string            { return proto.CompactTextString(m) }
func (*ServerSendBean) ProtoMessage()               {}
func (*ServerSendBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

const Default_ServerSendBean_ResultCode int32 = 0

type isServerSendBean_Bean interface {
	isServerSendBean_Bean()
}

type ServerSendBean_ResponseCreateroomBean struct {
	ResponseCreateroomBean *ServerResponseCreateRoomBean `protobuf:"bytes,5,opt,name=response_createroom_bean,json=responseCreateroomBean,oneof"`
}
type ServerSendBean_ResponseJoinroomBean struct {
	ResponseJoinroomBean *ServerResponseJoinRoomBean `protobuf:"bytes,6,opt,name=response_joinroom_bean,json=responseJoinroomBean,oneof"`
}
type ServerSendBean_PlayerJoinBean struct {
	PlayerJoinBean *PlagerJoinGameBean `protobuf:"bytes,7,opt,name=player_join_bean,json=playerJoinBean,oneof"`
}
type ServerSendBean_PlayerLevelBean struct {
	PlayerLevelBean *PlayerLeaveGameBean `protobuf:"bytes,8,opt,name=player_level_bean,json=playerLevelBean,oneof"`
}
type ServerSendBean_PlayerDeviceBean struct {
	PlayerDeviceBean *PlayerDeviceBean `protobuf:"bytes,9,opt,name=player_device_bean,json=playerDeviceBean,oneof"`
}
type ServerSendBean_PlayerHorsesgameSpeedBean struct {
	PlayerHorsesgameSpeedBean *HorseSpeedBean `protobuf:"bytes,10,opt,name=player_horsesgame_speed_bean,json=playerHorsesgameSpeedBean,oneof"`
}

func (*ServerSendBean_ResponseCreateroomBean) isServerSendBean_Bean()    {}
func (*ServerSendBean_ResponseJoinroomBean) isServerSendBean_Bean()      {}
func (*ServerSendBean_PlayerJoinBean) isServerSendBean_Bean()            {}
func (*ServerSendBean_PlayerLevelBean) isServerSendBean_Bean()           {}
func (*ServerSendBean_PlayerDeviceBean) isServerSendBean_Bean()          {}
func (*ServerSendBean_PlayerHorsesgameSpeedBean) isServerSendBean_Bean() {}

func (m *ServerSendBean) GetBean() isServerSendBean_Bean {
	if m != nil {
		return m.Bean
	}
	return nil
}

func (m *ServerSendBean) GetResultCode() int32 {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return Default_ServerSendBean_ResultCode
}

func (m *ServerSendBean) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *ServerSendBean) GetDesc() string {
	if m != nil && m.Desc != nil {
		return *m.Desc
	}
	return ""
}

func (m *ServerSendBean) GetOptionCode() RequestOperationCode {
	if m != nil && m.OptionCode != nil {
		return *m.OptionCode
	}
	return RequestOperationCode_REQUEST_OPERATIONCODE_PLAYERDEVICCEBEAN
}

func (m *ServerSendBean) GetResponseCreateroomBean() *ServerResponseCreateRoomBean {
	if x, ok := m.GetBean().(*ServerSendBean_ResponseCreateroomBean); ok {
		return x.ResponseCreateroomBean
	}
	return nil
}

func (m *ServerSendBean) GetResponseJoinroomBean() *ServerResponseJoinRoomBean {
	if x, ok := m.GetBean().(*ServerSendBean_ResponseJoinroomBean); ok {
		return x.ResponseJoinroomBean
	}
	return nil
}

func (m *ServerSendBean) GetPlayerJoinBean() *PlagerJoinGameBean {
	if x, ok := m.GetBean().(*ServerSendBean_PlayerJoinBean); ok {
		return x.PlayerJoinBean
	}
	return nil
}

func (m *ServerSendBean) GetPlayerLevelBean() *PlayerLeaveGameBean {
	if x, ok := m.GetBean().(*ServerSendBean_PlayerLevelBean); ok {
		return x.PlayerLevelBean
	}
	return nil
}

func (m *ServerSendBean) GetPlayerDeviceBean() *PlayerDeviceBean {
	if x, ok := m.GetBean().(*ServerSendBean_PlayerDeviceBean); ok {
		return x.PlayerDeviceBean
	}
	return nil
}

func (m *ServerSendBean) GetPlayerHorsesgameSpeedBean() *HorseSpeedBean {
	if x, ok := m.GetBean().(*ServerSendBean_PlayerHorsesgameSpeedBean); ok {
		return x.PlayerHorsesgameSpeedBean
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServerSendBean) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ServerSendBean_OneofMarshaler, _ServerSendBean_OneofUnmarshaler, _ServerSendBean_OneofSizer, []interface{}{
		(*ServerSendBean_ResponseCreateroomBean)(nil),
		(*ServerSendBean_ResponseJoinroomBean)(nil),
		(*ServerSendBean_PlayerJoinBean)(nil),
		(*ServerSendBean_PlayerLevelBean)(nil),
		(*ServerSendBean_PlayerDeviceBean)(nil),
		(*ServerSendBean_PlayerHorsesgameSpeedBean)(nil),
	}
}

func _ServerSendBean_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ServerSendBean)
	// Bean
	switch x := m.Bean.(type) {
	case *ServerSendBean_ResponseCreateroomBean:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResponseCreateroomBean); err != nil {
			return err
		}
	case *ServerSendBean_ResponseJoinroomBean:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResponseJoinroomBean); err != nil {
			return err
		}
	case *ServerSendBean_PlayerJoinBean:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerJoinBean); err != nil {
			return err
		}
	case *ServerSendBean_PlayerLevelBean:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerLevelBean); err != nil {
			return err
		}
	case *ServerSendBean_PlayerDeviceBean:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerDeviceBean); err != nil {
			return err
		}
	case *ServerSendBean_PlayerHorsesgameSpeedBean:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerHorsesgameSpeedBean); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServerSendBean.Bean has unexpected type %T", x)
	}
	return nil
}

func _ServerSendBean_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ServerSendBean)
	switch tag {
	case 5: // Bean.response_createroom_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ServerResponseCreateRoomBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ServerSendBean_ResponseCreateroomBean{msg}
		return true, err
	case 6: // Bean.response_joinroom_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ServerResponseJoinRoomBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ServerSendBean_ResponseJoinroomBean{msg}
		return true, err
	case 7: // Bean.player_join_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlagerJoinGameBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ServerSendBean_PlayerJoinBean{msg}
		return true, err
	case 8: // Bean.player_level_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlayerLeaveGameBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ServerSendBean_PlayerLevelBean{msg}
		return true, err
	case 9: // Bean.player_device_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlayerDeviceBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ServerSendBean_PlayerDeviceBean{msg}
		return true, err
	case 10: // Bean.player_horsesgame_speed_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HorseSpeedBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ServerSendBean_PlayerHorsesgameSpeedBean{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServerSendBean_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ServerSendBean)
	// Bean
	switch x := m.Bean.(type) {
	case *ServerSendBean_ResponseCreateroomBean:
		s := proto.Size(x.ResponseCreateroomBean)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerSendBean_ResponseJoinroomBean:
		s := proto.Size(x.ResponseJoinroomBean)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerSendBean_PlayerJoinBean:
		s := proto.Size(x.PlayerJoinBean)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerSendBean_PlayerLevelBean:
		s := proto.Size(x.PlayerLevelBean)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerSendBean_PlayerDeviceBean:
		s := proto.Size(x.PlayerDeviceBean)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServerSendBean_PlayerHorsesgameSpeedBean:
		s := proto.Size(x.PlayerHorsesgameSpeedBean)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// *
// client -> server
// client向server发送的数据
type ClientRequestBean struct {
	RequestId  *string               `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	OptionCode *RequestOperationCode `protobuf:"varint,2,opt,name=option_code,json=optionCode,enum=beans.RequestOperationCode" json:"option_code,omitempty"`
	// Types that are valid to be assigned to Bean:
	//	*ClientRequestBean_CreateroomBean
	//	*ClientRequestBean_JoinroomBean
	//	*ClientRequestBean_PlayerdeviceBean
	Bean             isClientRequestBean_Bean `protobuf_oneof:"Bean"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ClientRequestBean) Reset()                    { *m = ClientRequestBean{} }
func (m *ClientRequestBean) String() string            { return proto.CompactTextString(m) }
func (*ClientRequestBean) ProtoMessage()               {}
func (*ClientRequestBean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type isClientRequestBean_Bean interface {
	isClientRequestBean_Bean()
}

type ClientRequestBean_CreateroomBean struct {
	CreateroomBean *CreateRoomBean `protobuf:"bytes,3,opt,name=createroom_bean,json=createroomBean,oneof"`
}
type ClientRequestBean_JoinroomBean struct {
	JoinroomBean *JoinRoomBean `protobuf:"bytes,4,opt,name=joinroom_bean,json=joinroomBean,oneof"`
}
type ClientRequestBean_PlayerdeviceBean struct {
	PlayerdeviceBean *PlayerDeviceBean `protobuf:"bytes,5,opt,name=playerdevice_bean,json=playerdeviceBean,oneof"`
}

func (*ClientRequestBean_CreateroomBean) isClientRequestBean_Bean()   {}
func (*ClientRequestBean_JoinroomBean) isClientRequestBean_Bean()     {}
func (*ClientRequestBean_PlayerdeviceBean) isClientRequestBean_Bean() {}

func (m *ClientRequestBean) GetBean() isClientRequestBean_Bean {
	if m != nil {
		return m.Bean
	}
	return nil
}

func (m *ClientRequestBean) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *ClientRequestBean) GetOptionCode() RequestOperationCode {
	if m != nil && m.OptionCode != nil {
		return *m.OptionCode
	}
	return RequestOperationCode_REQUEST_OPERATIONCODE_PLAYERDEVICCEBEAN
}

func (m *ClientRequestBean) GetCreateroomBean() *CreateRoomBean {
	if x, ok := m.GetBean().(*ClientRequestBean_CreateroomBean); ok {
		return x.CreateroomBean
	}
	return nil
}

func (m *ClientRequestBean) GetJoinroomBean() *JoinRoomBean {
	if x, ok := m.GetBean().(*ClientRequestBean_JoinroomBean); ok {
		return x.JoinroomBean
	}
	return nil
}

func (m *ClientRequestBean) GetPlayerdeviceBean() *PlayerDeviceBean {
	if x, ok := m.GetBean().(*ClientRequestBean_PlayerdeviceBean); ok {
		return x.PlayerdeviceBean
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientRequestBean) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientRequestBean_OneofMarshaler, _ClientRequestBean_OneofUnmarshaler, _ClientRequestBean_OneofSizer, []interface{}{
		(*ClientRequestBean_CreateroomBean)(nil),
		(*ClientRequestBean_JoinroomBean)(nil),
		(*ClientRequestBean_PlayerdeviceBean)(nil),
	}
}

func _ClientRequestBean_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientRequestBean)
	// Bean
	switch x := m.Bean.(type) {
	case *ClientRequestBean_CreateroomBean:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CreateroomBean); err != nil {
			return err
		}
	case *ClientRequestBean_JoinroomBean:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.JoinroomBean); err != nil {
			return err
		}
	case *ClientRequestBean_PlayerdeviceBean:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PlayerdeviceBean); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClientRequestBean.Bean has unexpected type %T", x)
	}
	return nil
}

func _ClientRequestBean_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientRequestBean)
	switch tag {
	case 3: // Bean.createroom_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateRoomBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ClientRequestBean_CreateroomBean{msg}
		return true, err
	case 4: // Bean.joinroom_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JoinRoomBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ClientRequestBean_JoinroomBean{msg}
		return true, err
	case 5: // Bean.playerdevice_bean
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PlayerDeviceBean)
		err := b.DecodeMessage(msg)
		m.Bean = &ClientRequestBean_PlayerdeviceBean{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClientRequestBean_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientRequestBean)
	// Bean
	switch x := m.Bean.(type) {
	case *ClientRequestBean_CreateroomBean:
		s := proto.Size(x.CreateroomBean)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientRequestBean_JoinroomBean:
		s := proto.Size(x.JoinroomBean)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientRequestBean_PlayerdeviceBean:
		s := proto.Size(x.PlayerdeviceBean)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*CreateRoomBean)(nil), "beans.CreateRoomBean")
	proto.RegisterType((*JoinRoomBean)(nil), "beans.JoinRoomBean")
	proto.RegisterType((*PlayerDeviceBean)(nil), "beans.PlayerDeviceBean")
	proto.RegisterType((*PlagerJoinGameBean)(nil), "beans.PlagerJoinGameBean")
	proto.RegisterType((*PlayerLeaveGameBean)(nil), "beans.PlayerLeaveGameBean")
	proto.RegisterType((*HorseSpeedBean)(nil), "beans.HorseSpeedBean")
	proto.RegisterType((*ServerResponseCreateRoomBean)(nil), "beans.ServerResponseCreateRoomBean")
	proto.RegisterType((*ServerResponseJoinRoomBean)(nil), "beans.ServerResponseJoinRoomBean")
	proto.RegisterType((*ServerSendBean)(nil), "beans.ServerSendBean")
	proto.RegisterType((*ClientRequestBean)(nil), "beans.ClientRequestBean")
	proto.RegisterEnum("beans.RequestOperationCode", RequestOperationCode_name, RequestOperationCode_value)
	proto.RegisterEnum("beans.SendMessageOperationCode", SendMessageOperationCode_name, SendMessageOperationCode_value)
}

var fileDescriptor0 = []byte{
	// 974 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0x66, 0x65, 0x49, 0xb6, 0x5a, 0x8e, 0x22, 0x6f, 0x42, 0xa2, 0x84, 0x10, 0x9c, 0x0d, 0x15,
	0x82, 0x01, 0x57, 0x2a, 0x55, 0x5c, 0x5c, 0x1c, 0x90, 0xa5, 0xc1, 0x52, 0x2a, 0xd6, 0x8a, 0x59,
	0x03, 0x31, 0x97, 0xad, 0x8d, 0x34, 0x38, 0x0a, 0xeb, 0x5d, 0xb1, 0xbb, 0x76, 0x25, 0x54, 0xc1,
	0x1b, 0xf0, 0x06, 0x70, 0xe2, 0x29, 0xb8, 0xf0, 0x02, 0x3c, 0x04, 0xaf, 0x42, 0x4f, 0xcf, 0xec,
	0x6f, 0x14, 0x7e, 0x2e, 0xa6, 0x74, 0x90, 0xe6, 0xeb, 0xee, 0x6f, 0xbe, 0xee, 0xe9, 0x6e, 0xc1,
	0xd6, 0x53, 0xe1, 0x05, 0xf1, 0xee, 0xb3, 0x30, 0x8a, 0xc5, 0xee, 0x32, 0x0a, 0x93, 0xd0, 0x6c,
	0x10, 0x64, 0xfd, 0x6a, 0x40, 0x67, 0x10, 0x09, 0x2f, 0x11, 0x3c, 0x0c, 0x4f, 0xf7, 0x11, 0x33,
	0xaf, 0xc3, 0xfa, 0x89, 0x77, 0x2a, 0xdc, 0xc5, 0xbc, 0x67, 0x6c, 0x1b, 0xf7, 0x5b, 0xbc, 0x29,
	0x8f, 0xe3, 0xb9, 0xf9, 0x0e, 0xb4, 0xfc, 0x30, 0x38, 0x59, 0x24, 0x67, 0x73, 0xd1, 0xab, 0xa1,
	0xa9, 0xb6, 0x67, 0x3c, 0xe0, 0x39, 0x66, 0xbe, 0x0d, 0x1b, 0xbe, 0x97, 0x28, 0xfb, 0x5a, 0x6a,
	0xcf, 0x20, 0x24, 0xae, 0x2d, 0x96, 0xbd, 0xba, 0xe4, 0xdc, 0x5b, 0x7f, 0xb0, 0x4b, 0x1f, 0x8e,
	0x10, 0x12, 0xb7, 0xe7, 0xe2, 0x7c, 0x31, 0xc3, 0x3b, 0x83, 0x6f, 0xc2, 0x5e, 0x83, 0x6e, 0x05,
	0x05, 0x8d, 0x11, 0xb1, 0x7e, 0x33, 0x60, 0xf3, 0x51, 0xb8, 0x08, 0x56, 0x69, 0x6c, 0x96, 0x34,
	0x5e, 0x83, 0x66, 0x12, 0xce, 0xbe, 0x15, 0x41, 0xaa, 0x5d, 0x9d, 0xfe, 0x47, 0xed, 0x7f, 0xd6,
	0xa0, 0x3b, 0xf5, 0xbd, 0x97, 0x22, 0x1a, 0x12, 0x48, 0xfa, 0x73, 0x99, 0xed, 0x92, 0xcc, 0x42,
	0x5e, 0x50, 0xca, 0xcb, 0x82, 0xb6, 0x17, 0x9c, 0xf8, 0xc2, 0xf5, 0xfc, 0xe5, 0x33, 0x8f, 0x92,
	0x23, 0x85, 0x40, 0x68, 0x5f, 0x82, 0xe6, 0x36, 0xa8, 0x93, 0xfb, 0x54, 0x24, 0x5e, 0x21, 0x49,
	0x02, 0xf7, 0x11, 0xcb, 0x59, 0x90, 0xf5, 0xd4, 0xcb, 0xf3, 0x54, 0x71, 0x07, 0x12, 0x34, 0x7b,
	0xd0, 0xf4, 0x66, 0x98, 0xce, 0x0b, 0xca, 0x96, 0xcc, 0x0d, 0x09, 0x3c, 0xc9, 0x2c, 0x2f, 0x29,
	0xcb, 0xdc, 0x72, 0x9c, 0x59, 0xbe, 0xa7, 0xd7, 0xc8, 0x2d, 0x5f, 0x93, 0x26, 0x69, 0x51, 0xb2,
	0xd7, 0x73, 0x4d, 0x08, 0x2a, 0xd5, 0xb7, 0x81, 0x0e, 0x4a, 0xf4, 0x46, 0x56, 0x79, 0x89, 0x91,
	0xe6, 0x94, 0x41, 0x49, 0x6e, 0x95, 0x18, 0x48, 0xb1, 0xf5, 0x03, 0x98, 0x58, 0xe0, 0x13, 0x11,
	0xc9, 0x16, 0x41, 0x48, 0x95, 0xf8, 0x2e, 0x5c, 0x5a, 0x52, 0xd9, 0xdd, 0x52, 0x43, 0x6c, 0x2a,
	0xf0, 0x28, 0x6d, 0x8b, 0xb6, 0x76, 0x0a, 0x30, 0x8e, 0x6a, 0x86, 0xaf, 0xa7, 0xa0, 0x09, 0x22,
	0xe6, 0x1d, 0xd0, 0x01, 0xae, 0x2f, 0xce, 0x85, 0x4f, 0x25, 0x6b, 0x70, 0x1d, 0xf4, 0x58, 0x42,
	0xd6, 0x8f, 0x70, 0x65, 0xaa, 0x8f, 0xde, 0xb9, 0xb8, 0xf8, 0xfb, 0x7f, 0xc6, 0x11, 0x1e, 0xc9,
	0xc9, 0x76, 0x96, 0x42, 0xcc, 0x2f, 0xf4, 0xee, 0x82, 0x4b, 0x2c, 0x2f, 0x57, 0x2d, 0x93, 0xba,
	0x90, 0x1e, 0xeb, 0x2b, 0xb8, 0xe5, 0x88, 0xe8, 0x5c, 0x44, 0x5c, 0xc4, 0xcb, 0x30, 0x88, 0x45,
	0x65, 0xdd, 0xe0, 0xfb, 0x9f, 0x7a, 0x2f, 0xdc, 0x59, 0x78, 0x16, 0x24, 0xa4, 0xb3, 0x41, 0xef,
	0x8f, 0xd8, 0x40, 0x42, 0x72, 0x24, 0x22, 0xf4, 0x95, 0x23, 0xa1, 0x24, 0x36, 0xe5, 0x71, 0x3c,
	0xb7, 0x3e, 0x86, 0x9b, 0x65, 0xe2, 0xea, 0x86, 0x48, 0xc3, 0x8c, 0x52, 0xd8, 0x2f, 0x0d, 0xe8,
	0xa8, 0x38, 0x47, 0x04, 0xaa, 0x5c, 0x38, 0x16, 0x91, 0x88, 0xcf, 0xfc, 0x04, 0x55, 0xe0, 0xf8,
	0x67, 0x22, 0x40, 0xa1, 0x83, 0x90, 0xf6, 0x03, 0x9e, 0xbe, 0x3b, 0x13, 0x71, 0x92, 0x2b, 0x69,
	0x69, 0x04, 0xe7, 0xd3, 0x84, 0xfa, 0x5c, 0xc4, 0x33, 0xaa, 0x51, 0x8b, 0xd3, 0x6f, 0xf3, 0x13,
	0x68, 0x87, 0xcb, 0x64, 0x11, 0x06, 0x8a, 0x56, 0xd6, 0xa6, 0xf3, 0xf0, 0xad, 0x5d, 0xb5, 0x8b,
	0xb9, 0x0a, 0xb5, 0x97, 0x22, 0xf2, 0xa4, 0x8f, 0xbc, 0x84, 0x83, 0xf2, 0xa7, 0x0b, 0x5d, 0xe8,
	0x45, 0x3a, 0x31, 0x77, 0x46, 0x25, 0xa3, 0x7c, 0x64, 0x34, 0xcd, 0x5f, 0xfb, 0xe1, 0x5d, 0x4d,
	0xf5, 0x77, 0xe5, 0x1d, 0xbd, 0xc1, 0xaf, 0x45, 0x25, 0x4b, 0x94, 0x56, 0xe8, 0x18, 0x32, 0x8b,
	0xfb, 0x1c, 0x4b, 0x97, 0xd3, 0x37, 0x89, 0xfe, 0xce, 0x4a, 0xfa, 0x62, 0x91, 0x91, 0xfc, 0x6a,
	0x54, 0xc0, 0x33, 0x6a, 0x06, 0x5d, 0xdd, 0x16, 0x92, 0x58, 0x91, 0xae, 0x13, 0xe9, 0x0d, 0x4d,
	0xfa, 0xea, 0xc0, 0x22, 0x59, 0x47, 0x05, 0x49, 0x94, 0x68, 0x46, 0xb0, 0x55, 0x6c, 0x40, 0xc5,
	0xb3, 0x41, 0x3c, 0x37, 0x73, 0x9e, 0xea, 0xe4, 0x21, 0xd1, 0xe5, 0x42, 0x8f, 0x12, 0xd3, 0x01,
	0x98, 0x9a, 0x49, 0x2f, 0x6b, 0xa2, 0x6a, 0x11, 0xd5, 0xf5, 0x12, 0x55, 0xbe, 0xa4, 0x91, 0x47,
	0x67, 0x51, 0x58, 0xdc, 0x4f, 0xe0, 0x96, 0x26, 0xa2, 0x3f, 0xd3, 0x98, 0xb6, 0x35, 0xf5, 0xbe,
	0xa2, 0x04, 0xa2, 0x7c, 0x53, 0x53, 0x96, 0xc7, 0x12, 0x09, 0x6f, 0xa8, 0xe0, 0x51, 0x16, 0x9b,
	0x19, 0xf7, 0x9b, 0x50, 0x97, 0xdf, 0xd6, 0xef, 0x35, 0xd8, 0x1a, 0xf8, 0x0b, 0x11, 0x24, 0xba,
	0x45, 0xe8, 0xde, 0x72, 0xfb, 0x19, 0xd5, 0xf6, 0xab, 0xb4, 0x5a, 0xed, 0xbf, 0xb5, 0xda, 0xa7,
	0x70, 0xb9, 0xda, 0x61, 0x6b, 0xa5, 0x3c, 0x5e, 0xe9, 0xa9, 0xce, 0xac, 0xdc, 0x4b, 0x7b, 0x70,
	0xa9, 0xdc, 0x42, 0x75, 0x8a, 0xbf, 0xa2, 0xe3, 0x2b, 0x4d, 0xb3, 0xf9, 0xbc, 0xd8, 0x2c, 0x9f,
	0xa5, 0xaf, 0x5c, 0x7c, 0x9a, 0xc6, 0xbf, 0x7c, 0x9a, 0x79, 0x86, 0xa5, 0x05, 0xdc, 0xf9, 0xc9,
	0x80, 0xab, 0xab, 0x52, 0x36, 0x3f, 0x80, 0xf7, 0x38, 0xfb, 0xfc, 0x0b, 0xe6, 0x1c, 0xb9, 0xf6,
	0x94, 0xf1, 0xfe, 0xd1, 0xd8, 0x9e, 0x0c, 0xec, 0x21, 0x73, 0xa7, 0x8f, 0xfb, 0xc7, 0x8c, 0x0f,
	0xd9, 0x97, 0xe3, 0xc1, 0x80, 0xed, 0xb3, 0xfe, 0xa4, 0x6b, 0x98, 0xef, 0xc2, 0xf6, 0x6a, 0xe7,
	0x01, 0x67, 0xfd, 0x23, 0xc6, 0x6d, 0xfb, 0xb0, 0x5b, 0xc3, 0xcd, 0x71, 0x7b, 0xb5, 0xd7, 0x23,
	0x7b, 0x3c, 0x21, 0x9f, 0xb5, 0x9d, 0x3f, 0x0c, 0xe8, 0xc9, 0x55, 0x73, 0x28, 0xe2, 0x18, 0x9b,
	0xbe, 0xac, 0xe9, 0x1e, 0x58, 0x0e, 0x9b, 0x0c, 0x0f, 0x99, 0xe3, 0xf4, 0x0f, 0x58, 0x85, 0x84,
	0x33, 0x67, 0x6a, 0x4f, 0x1c, 0x86, 0x72, 0x3e, 0x84, 0xfb, 0xaf, 0xf7, 0x53, 0xfa, 0xe5, 0x95,
	0x07, 0xfd, 0x43, 0x86, 0xb2, 0x76, 0xe0, 0xde, 0x3f, 0x79, 0x53, 0xb6, 0xac, 0xbb, 0x66, 0x7e,
	0x04, 0xef, 0xbf, 0xde, 0x77, 0x64, 0x73, 0x87, 0x49, 0x52, 0xd7, 0x99, 0x32, 0x36, 0xec, 0xd6,
	0xff, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x1b, 0x6b, 0x7d, 0x4b, 0x0a, 0x00, 0x00,
}
